### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by mingyEx** [romaonishuk/LexI#2]
Hello, I am from [here](https://stackoverflow.com/questions/4829227/gang-of-four-lexi-editor-c-source/61875132?noredirect=1#comment127195211_61875132), I tried to build this project , encountered the following problem.

##### 1. Invalid cl parameter
 a similar problem like [this](https://stackoverflow.com/questions/2274006/cmake-invalid-numeric-argument-wextra) but I didn't find what the gcc option corresponds to in msvc, so I deleted all the options [here](https://github.com/romaonishuk/LexI/blob/windows/CMakeLists.txt#L13) .

#### 2. Cannot open include file: 'x_window_impl.hpp': No such file or directory C:\Users\xx\Documents\GitHub\LexI\src\window_system_factory.cpp

i find [this](https://stackoverflow.com/a/44823903/13792395)
But I only know how to set the header files for `*.sln` projects, I don't know how to set up cmake, and it seems that your don't handle it [correctly](https://github.com/romaonishuk/LexI/blob/windows/CMakeLists.txt#L35)?

#### 3. The problem of type conversion:
https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-1-c4838?view=msvc-170
I added static_cast<int32_t>() to each error line

**Comment by romaonishuk** [comment]
Hi @KargathEx 
I will add fixes to the windows branch in a few days.

Regarding your question:
1. I didn't think about msvc as my main compiler from the start, but it does support most of used flags, but without dash, ex: -Wall for gcc equal to /Wall in msvc/
2. I'll check this, but the main issue is that x_window_impl is an implementation for the XLib - low-level GUI lib for Linux and for windows w_windows_imple should be used. I assume the issue is related to CMake, since this file is disabled by ifdef in code coming from the CMake.
Comment in code relates to the difference in CMake for Windows and Linux (or maybe it's just a difference between the ones I have installed in my system)
3. I assume, it could be fixed by adding changing int32_t to std::int32_t

**Comment by romaonishuk** [comment]
@KargathEx I have fixed this issue on my side, pls try the soulution

**Comment by mingyEx** [comment]
I build it successfully。
Although the interface is a bit rough.
What are your next steps to add?

**Comment by romaonishuk** [comment]
@KargathEx 
first of all - finish migration on Windows, a lot of functionality is not added yet. So both versions, for Linux and Windows work similarly. And then, functionality extension (https://github.com/romaonishuk/LexI#todo-list).
and making a good looking UI)

P.S. I believe we can close this issue?

**Comment by mingyEx** [comment]
yes! Thanks for your patience
